#!/bin/bash
# 
AXIOM_PATH="$HOME/.axiom"
source "$AXIOM_PATH/interact/includes/vars.sh"
if [[ -f "$AXIOM_PATH/docker/config/id_rsa" ]] && [[ -f "$AXIOM_PATH/docker/config/id_rsa.pub" ]]; 
then
    mkdir /root/.ssh
    cp "$AXIOM_PATH/docker/config/id_rsa.pub" /root/.ssh/id_rsa.pub
    cp "$AXIOM_PATH/docker/config/id_rsa" /root/.ssh/id_rsa
    echo -e "${Green}SSH keys set${Color_Off}"
else 
    echo -e "${Red}Could not find SSH Keys. ${Color_Off}"
fi


